<script type="text/javascript">
$().ready(function() {$("#tree").treeview({collapsed: true,control:"#sidetreecontrol",prerendered: false,persist: "location"});});
</script>
<?php if(count($this->_tpl_vars['array']) > 0){ ?>
<ul id="tree">
<?php if (count($this->_tpl_vars['array'])>0){$divid_list=1;for($list=0;$list<count($this->_tpl_vars['array']); $list++){?>
	<li class="open">
	<div class="infolist" onselectstart="return false;">
	     <table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
			<tr>
				<td width="3%"><input type="checkbox" name="selectinfoid" value="<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>"></td>
				<td width="6%">
					<input type="hidden" name="infoid" id="infoid" value="<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>">
					<input type="text" name="pid" size="1" value="<?php echo $this->_tpl_vars['array'][$list]['pid'] ?>" class="infoInput" style="width:25px;"  onclick="if (this.value == '<?php echo $this->_tpl_vars['array'][$list]['pid'] ?>'){this.value = ''; } else {this.select(); }" onblur="if (this.value == ''){this.value = '<?php echo $this->_tpl_vars['array'][$list]['pid'] ?>'; }">
				</td>
				<td width="5%"><?php echo $this->_tpl_vars['array'][$list]['tid'] ?></td>
				<td width="22%" id="left"<?php if(count( $this->_tpl_vars['array'][$list]['childArray'] ) <= 0){ ?> class="onefast"<?php } ?>><a target="_blank" class="infolink04b" href="<?php echo $this->_tpl_vars['array'][$list]['glink'] ?>"><?php echo $this->_tpl_vars['array'][$list]['typename'] ?></a></td>
				<td width="8%"><?php echo $this->_tpl_vars['array'][$list]['stylename'] ?></td>
				<td width="56%" id="infotype">
					<table border="0" style="border-collapse:collapse" bordercolor="#FFFFFF">
						<tr>
							<?php if($this->_tpl_vars['array'][$list]['styleid']<3){ ?>
							<td><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>', 'index.php?archive=management&action=list&listfunction=articlelist&tid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&mid=<?php echo $this->_tpl_vars['array'][$list]['mid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), true, 'typelist<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typelist<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['viewfield_botton'] ?></a></td>
							<?php } ?>
							<?php if($this->powercheck('article','typeadd')==true ){ ?>
							<td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['topid'] ?>&styleid=1&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?></a></td>
							<td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['topid'] ?>&styleid=4&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title2'] ?></a></td>
							<td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['topid'] ?>&styleid=3&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title3'] ?></a></td>
							<?php } ?>
							<?php if($this->powercheck('article','typeedit')==true ){ ?>
							<td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>', 'index.php?archive=typemanage&action=typeedit&tid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&type=edit&styleid=<?php echo $this->_tpl_vars['array'][$list]['styleid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeedit<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeedit<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setedit_botton'] ?></a></td>
							<?php } ?>
							<?php if($this->powercheck('article','typeedit')==true && $this->_tpl_vars['array'][$list]['styleid']<3){ ?>
							<td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>', 'index.php?archive=typemanage&action=typeshift&tid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&styleid=<?php echo $this->_tpl_vars['array'][$list]['styleid'] ?>&type=edit&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['typename'] ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?></a></td>
							<?php } ?>
							<?php if($this->powercheck('article','synchro')==true && $this->_tpl_vars['array'][$list]['styleid']<3){ ?>
							<td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>', 'index.php?archive=typemanage&action=synchro&tid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['botton_synchro_slow'] ?></a></td>
							<?php } ?>
							<?php if($this->powercheck('article','deltype')==true ){ ?>
							<td class="padding-left3"><a class="setedit" onclick="javascript:submiturl('index.php?archive=typemanage&action=deltype&tid=<?php echo $this->_tpl_vars['array'][$list]['tid'] ?>&freshid=' + Math.random(), 'index.php?archive=management&action=load', '<?php echo $this->_tpl_vars['ST']['run_ok'] ?>', '<?php echo $this->_tpl_vars['ST']['run_no'] ?>', true, '<?php echo $this->_tpl_vars['ST']['del_messok'] ?>', 'selectform', 'selectall', 'check_all');" href="#body" title="<?php echo $this->_tpl_vars['ST']['setdel_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setdel_botton'] ?></a></td>
							<?php } ?>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
	<?php if(count( $this->_tpl_vars['array'][$list]['childArray'] ) > 0){ ?>
		<ul>
		<?php if (count($this->_tpl_vars['array'][$list]['childArray'])>0){$divid_ii=1;for($ii=0;$ii<count($this->_tpl_vars['array'][$list]['childArray']); $ii++){?>
			<li class="open">
			<div class="infolist" onselectstart="return false;">
				<table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
					   <tr>
						   <td width="3%"><input type="checkbox" name="selectinfoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>"></td>
						   <td width="6%">
							   <input type="hidden" name="infoid" id="infoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>">
							   <input type="text" name="pid" size="1" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['pid'] ?>" class="infoInput" style="width:25px;"  onclick="if (this.value == '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['pid'] ?>'){this.value = ''; } else {this.select(); }" onblur="if (this.value == ''){this.value = '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['pid'] ?>'; }">
						   </td>
						   <td width="5%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?></td>
						   <td width="22%" id="left" class="one"><a target="_blank" class="infolink04" href="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['glink'] ?>"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'] ?></a></td>
						   <td width="8%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['stylename'] ?></td>
						   <td width="56%" id="infotype">
							   <table border="0" style="border-collapse:collapse" bordercolor="#FFFFFF">
								   <tr>
									   <?php if($this->_tpl_vars['array'][$list]['childArray'][$ii]['styleid']<3){ ?>
									   <td><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>', 'index.php?archive=management&action=list&listfunction=articlelist&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&mid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['mid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), true, 'typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['viewfield_botton'] ?></a></td>
									   <?php } ?>
									   <?php if($this->powercheck('article','typeadd')==true ){ ?>
									   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['topid'] ?>&styleid=1&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?></a></td>
									   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['topid'] ?>&styleid=4&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title2'] ?></a></td>
									   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['topid'] ?>&styleid=3&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title3'] ?></a></td>
									   <?php } ?>
									   <?php if($this->powercheck('article','typeedit')==true ){ ?>
									   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>', 'index.php?archive=typemanage&action=typeedit&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&type=edit&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['styleid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setedit_botton'] ?></a></td>
									   <?php } ?>
									   <?php if($this->powercheck('article','typeedit')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['styleid']<3){ ?>
									   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>', 'index.php?archive=typemanage&action=typeshift&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['styleid'] ?>&type=edit&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?></a></td>
									   <?php } ?>
									   <?php if($this->powercheck('article','synchro')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['styleid']<3){ ?>
									   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>', 'index.php?archive=typemanage&action=synchro&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['botton_synchro_slow'] ?></a></td>
									   <?php } ?>
									   <?php if($this->powercheck('article','deltype')==true ){ ?>
									   <td class="padding-left3"><a class="setedit" onclick="javascript:submiturl('index.php?archive=typemanage&action=deltype&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['tid'] ?>&freshid=' + Math.random(), 'index.php?archive=management&action=load', '<?php echo $this->_tpl_vars['ST']['run_ok'] ?>', '<?php echo $this->_tpl_vars['ST']['run_no'] ?>', true, '<?php echo $this->_tpl_vars['ST']['del_messok'] ?>', 'selectform', 'selectall', 'check_all');" href="#body" title="<?php echo $this->_tpl_vars['ST']['setdel_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setdel_botton'] ?></a></td>
									   <?php } ?>
								   </tr>
							</table>
						</td>
					</tr>
				 </table>
			 </div>

			<?php if(count( $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'] ) > 0){ ?>
				<ul>
				<?php if (count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'])>0){$divid_iii=1;for($iii=0;$iii<count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray']); $iii++){?>
					<li class="open">
					<div class="infolist" onselectstart="return false;">
						<table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
							   <tr>
								   <td width="3%"><input type="checkbox" name="selectinfoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>"></td>
								   <td width="6%">
									   <input type="hidden" name="infoid" id="infoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>">
									   <input type="text" name="pid" size="1" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['pid'] ?>" class="infoInput" style="width:25px;"  onclick="if (this.value == '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['pid'] ?>'){this.value = ''; } else {this.select(); }" onblur="if (this.value == ''){this.value = '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['pid'] ?>'; }">
								   </td>
								   <td width="5%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?></td>
								   <td width="22%" id="left" class="tow"><a target="_blank" class="infolink04" href="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['glink'] ?>"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'] ?></a></td>
								   <td width="8%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['stylename'] ?></td>
								   <td width="56%" id="infotype">
									   <table border="0" style="border-collapse:collapse" bordercolor="#FFFFFF">
										   <tr>
											   <?php if($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['styleid']<3){ ?>
											   <td><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>', 'index.php?archive=management&action=list&listfunction=articlelist&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&mid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['mid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), true, 'typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['viewfield_botton'] ?></a></td>
											   <?php } ?>
											   <?php if($this->powercheck('article','typeadd')==true ){ ?>
											   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['topid'] ?>&styleid=1&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?></a></td>
											   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['topid'] ?>&styleid=4&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title2'] ?></a></td>
											   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['topid'] ?>&styleid=3&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title3'] ?></a></td>
											   <?php } ?>
											   <?php if($this->powercheck('article','typeedit')==true ){ ?>
											   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>', 'index.php?archive=typemanage&action=typeedit&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&type=edit&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['styleid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setedit_botton'] ?></a></td>
											   <?php } ?>
											   <?php if($this->powercheck('article','typeedit')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['styleid']<3){ ?>
											   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>', 'index.php?archive=typemanage&action=typeshift&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['styleid'] ?>&type=edit&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?></a></td>
											   <?php } ?>
											   <?php if($this->powercheck('article','synchro')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['styleid']<3){ ?>
											   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>', 'index.php?archive=typemanage&action=synchro&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['botton_synchro_slow'] ?></a></td>
											   <?php } ?>
											   <?php if($this->powercheck('article','deltype')==true ){ ?>
											   <td class="padding-left3"><a class="setedit" onclick="javascript:submiturl('index.php?archive=typemanage&action=deltype&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['tid'] ?>&freshid=' + Math.random(), 'index.php?archive=management&action=load', '<?php echo $this->_tpl_vars['ST']['run_ok'] ?>', '<?php echo $this->_tpl_vars['ST']['run_no'] ?>', true, '<?php echo $this->_tpl_vars['ST']['del_messok'] ?>', 'selectform', 'selectall', 'check_all');" href="#body" title="<?php echo $this->_tpl_vars['ST']['setdel_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setdel_botton'] ?></a></td>
											   <?php } ?>
										   </tr>
									   </table>
								   </td>
							   </tr>
						   </table>
					</div>
						<?php if(count( $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'] ) > 0){ ?>
							<ul>
							<?php if (count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'])>0){$divid_iiii=1;for($iiii=0;$iiii<count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray']); $iiii++){?>
								<li class="open">
									<div class="infolist" onselectstart="return false;">
									<table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
										   <tr>
											   <td width="3%"><input type="checkbox" name="selectinfoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>"></td>
											   <td width="6%">
												   <input type="hidden" name="infoid" id="infoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>">
												   <input type="text" name="pid" size="1" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['pid'] ?>" class="infoInput" style="width:25px;"  onclick="if (this.value == '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['pid'] ?>'){this.value = ''; } else {this.select(); }" onblur="if (this.value == ''){this.value = '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['pid'] ?>'; }">
											   </td>
											   <td width="5%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?></td>
											   <td width="22%" id="left" class="four"><a target="_blank" class="infolink04" href="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['glink'] ?>"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'] ?></a></td>
											   <td width="8%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['stylename'] ?></td>
											   <td width="56%" id="infotype">
												   <table border="0" style="border-collapse:collapse" bordercolor="#FFFFFF">
													   <tr>
														   <?php if($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['styleid']<3){ ?>
														   <td><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>', 'index.php?archive=management&action=list&listfunction=articlelist&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&mid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['mid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), true, 'typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['viewfield_botton'] ?></a></td>
														   <?php } ?>
														   <?php if($this->powercheck('article','typeadd')==true ){ ?>
														   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['topid'] ?>&styleid=1&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?></a></td>
														   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['topid'] ?>&styleid=4&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title2'] ?></a></td>
														   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['topid'] ?>&styleid=3&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title3'] ?></a></td>
														   <?php } ?>
														   <?php if($this->powercheck('article','typeedit')==true ){ ?>
														   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>', 'index.php?archive=typemanage&action=typeedit&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&type=edit&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['styleid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setedit_botton'] ?></a></td>
														   <?php } ?>
														   <?php if($this->powercheck('article','typeedit')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['styleid']<3){ ?>
														   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>', 'index.php?archive=typemanage&action=typeshift&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['styleid'] ?>&type=edit&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?></a></td>
														   <?php } ?>
														   <?php if($this->powercheck('article','synchro')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['styleid']<3){ ?>
														   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>', 'index.php?archive=typemanage&action=synchro&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['botton_synchro_slow'] ?></a></td>
														   <?php } ?>
														   <?php if($this->powercheck('article','deltype')==true ){ ?>
														   <td class="padding-left3"><a class="setedit" onclick="javascript:submiturl('index.php?archive=typemanage&action=deltype&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['tid'] ?>&freshid=' + Math.random(), 'index.php?archive=management&action=load', '<?php echo $this->_tpl_vars['ST']['run_ok'] ?>', '<?php echo $this->_tpl_vars['ST']['run_no'] ?>', true, '<?php echo $this->_tpl_vars['ST']['del_messok'] ?>', 'selectform', 'selectall', 'check_all');" href="#body" title="<?php echo $this->_tpl_vars['ST']['setdel_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setdel_botton'] ?></a></td>
														   <?php } ?>
													   </tr>
												   </table>
											   </td>
										   </tr>
									   </table>
									</div>


									<?php if(count( $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'] ) > 0){ ?>
										<ul>
										<?php if (count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'])>0){$divid_iiiii=1;for($iiiii=0;$iiiii<count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray']); $iiiii++){?>
											<li class="open">
												<div class="infolist" onselectstart="return false;">
													<table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
														   <tr>
															   <td width="3%"><input type="checkbox" name="selectinfoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>"></td>
															   <td width="6%">
																   <input type="hidden" name="infoid" id="infoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>">
																   <input type="text" name="pid" size="1" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['pid'] ?>" class="infoInput" style="width:25px;"  onclick="if (this.value == '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['pid'] ?>'){this.value = ''; } else {this.select(); }" onblur="if (this.value == ''){this.value = '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['pid'] ?>'; }">
															   </td>
															   <td width="5%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?></td>
															   <td width="22%" id="left" class="five"><a target="_blank" class="infolink04" href="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['glink'] ?>"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'] ?></a></td>
															   <td width="8%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['stylename'] ?></td>
															   <td width="56%" id="infotype">
																   <table border="0" style="border-collapse:collapse" bordercolor="#FFFFFF">
																	   <tr>
																		   <?php if($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['styleid']<3){ ?>
																		   <td><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>', 'index.php?archive=management&action=list&listfunction=articlelist&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&mid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['mid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), true, 'typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['viewfield_botton'] ?></a></td>
																		   <?php } ?>
																		   <?php if($this->powercheck('article','typeadd')==true ){ ?>
																		   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['topid'] ?>&styleid=1&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?></a></td>
																		   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['topid'] ?>&styleid=4&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title2'] ?></a></td>
																		   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['topid'] ?>&styleid=3&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title3'] ?></a></td>
																		   <?php } ?>
																		   <?php if($this->powercheck('article','typeedit')==true ){ ?>
																		   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>', 'index.php?archive=typemanage&action=typeedit&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&type=edit&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['styleid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setedit_botton'] ?></a></td>
																		   <?php } ?>
																		   <?php if($this->powercheck('article','typeedit')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['styleid']<3){ ?>
																		   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>', 'index.php?archive=typemanage&action=typeshift&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['styleid'] ?>&type=edit&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?></a></td>
																		   <?php } ?>
																		   <?php if($this->powercheck('article','synchro')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['styleid']<3){ ?>
																		   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>', 'index.php?archive=typemanage&action=synchro&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['botton_synchro_slow'] ?></a></td>
																		   <?php } ?>
																		   <?php if($this->powercheck('article','deltype')==true ){ ?>
																		   <td class="padding-left3"><a class="setedit" onclick="javascript:submiturl('index.php?archive=typemanage&action=deltype&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['tid'] ?>&freshid=' + Math.random(), 'index.php?archive=management&action=load', '<?php echo $this->_tpl_vars['ST']['run_ok'] ?>', '<?php echo $this->_tpl_vars['ST']['run_no'] ?>', true, '<?php echo $this->_tpl_vars['ST']['del_messok'] ?>', 'selectform', 'selectall', 'check_all');" href="#body" title="<?php echo $this->_tpl_vars['ST']['setdel_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setdel_botton'] ?></a></td>
																		   <?php } ?>
																	   </tr>
																   </table>
															   </td>
														   </tr>
													   </table>
												</div>
												<?php if(count( $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'] ) > 0){ ?>
													<ul>
													<?php if (count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'])>0){$divid_iiiiii=1;for($iiiiii=0;$iiiiii<count($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray']); $iiiiii++){?>
														<li class="open">
															<div class="infolist" onselectstart="return false;">
																<table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
																	   <tr>
																		   <td width="3%"><input type="checkbox" name="selectinfoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>"></td>
																		   <td width="6%">
																			   <input type="hidden" name="infoid" id="infoid" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>">
																			   <input type="text" name="pid" size="1" value="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['pid'] ?>" class="infoInput" style="width:25px;"  onclick="if (this.value == '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['pid'] ?>'){this.value = ''; } else {this.select(); }" onblur="if (this.value == ''){this.value = '<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['pid'] ?>'; }">
																		   </td>
																		   <td width="5%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?></td>
																		   <td width="22%" id="left" class="six"><a target="_blank" class="infolink04" href="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['glink'] ?>"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'] ?></a></td>
																		   <td width="8%"><?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['stylename'] ?></td>
																		   <td width="56%" id="infotype">
																			   <table border="0" style="border-collapse:collapse" bordercolor="#FFFFFF">
																				   <tr>
																					   <?php if($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['styleid']<3){ ?>
																					   <td><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>', 'index.php?archive=management&action=list&listfunction=articlelist&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&mid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['mid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), true, 'typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typelist<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['ST']['typemanage_text_infolist_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['viewfield_botton'] ?></a></td>
																					   <?php } ?>
																					   <?php if($this->powercheck('article','typeadd')==true ){ ?>
																					   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['topid'] ?>&styleid=1&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?></a></td>
																					   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['topid'] ?>&styleid=4&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title2'] ?></a></td>
																					   <td class="padding-left3"><a class="setedit2" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>', 'index.php?archive=typemanage&action=typeadd&upid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&lng=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['lng'] ?>&topid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['topid'] ?>&styleid=3&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeadd<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_add_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typemanage_add_title3'] ?></a></td>
																					   <?php } ?>
																					   <?php if($this->powercheck('article','typeedit')==true ){ ?>
																					   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>', 'index.php?archive=typemanage&action=typeedit&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&type=edit&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['styleid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false, 'typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>', self.frameElement.getAttribute('name'));" id="typeedit<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typemanage_edit_title'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setedit_botton'] ?></a></td>
																					   <?php } ?>
																					   <?php if($this->powercheck('article','typeedit')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['styleid']<3){ ?>
																					   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->addslashes($this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'],'hc') ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>', 'index.php?archive=typemanage&action=typeshift&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&styleid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['styleid'] ?>&type=edit&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['typename'] ?><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['typeshift_botton'] ?></a></td>
																					   <?php } ?>
																					   <?php if($this->powercheck('article','synchro')==true && $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['styleid']<3){ ?>
																					   <td class="padding-left3"><a class="setedit" onclick="javascript:parent.onbotton('<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>', 'index.php?archive=typemanage&action=synchro&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&freshid=' + Math.random() + '&iframename=' + self.frameElement.getAttribute('name'), false);" href="#body" title="<?php echo $this->_tpl_vars['ST']['botton_synchro'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['botton_synchro_slow'] ?></a></td>
																					   <?php } ?>
																					   <?php if($this->powercheck('article','deltype')==true ){ ?>
																					   <td class="padding-left3"><a class="setedit" onclick="javascript:submiturl('index.php?archive=typemanage&action=deltype&tid=<?php echo $this->_tpl_vars['array'][$list]['childArray'][$ii]['childArray'][$iii]['childArray'][$iiii]['childArray'][$iiiii]['childArray'][$iiiiii]['tid'] ?>&freshid=' + Math.random(), 'index.php?archive=management&action=load', '<?php echo $this->_tpl_vars['ST']['run_ok'] ?>', '<?php echo $this->_tpl_vars['ST']['run_no'] ?>', true, '<?php echo $this->_tpl_vars['ST']['del_messok'] ?>', 'selectform', 'selectall', 'check_all');" href="#body" title="<?php echo $this->_tpl_vars['ST']['setdel_botton'] ?>" hidefocus="true"><?php echo $this->_tpl_vars['ST']['setdel_botton'] ?></a></td>
																					   <?php } ?>
																				   </tr>
																			   </table>
																		   </td>
																	   </tr>
																   </table>
															</div>
														</li>
													<?php }} ?>
													</ul>
												<?php } ?>
											</li>
										<?php }} ?>
										</ul>
									<?php } ?>
								</li>
							<?php }} ?>
							</ul>
						<?php } ?>
					</li>
				<?php }} ?>
				</ul>
			<?php } ?>
			</li>
		<?php }} ?>
		</ul>
	<?php } ?>
	</li>
<?php }} ?>
</ul>
<?php }else{ ?>
<div class="infolist">
	<table border="0" style="border-collapse:collapse" width="100%" bordercolor="#FFFFFF">
		<tr>
			<td align="center"><?php echo $this->_tpl_vars['ST']['list_nothing_title'] ?></td>
		</tr>
	</table>
</div>
<?php } ?>      